import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  OneToMany,
  Index,
} from 'typeorm';
import { Venue } from '@modules/venues/entities/venue.entity';
import { Format } from '@modules/formats/entities/format.entity';
import { MatchPlayer } from './match-player.entity';
import { MatchTeam } from './match-team.entity';
import { MatchMessage } from '@modules/messages/entities/match-message.entity';
import { MatchStatus, MATCH_STATUSES } from '@shared/match';

/**
 * Match entity representing a basketball match.
 *
 * Core business entity produced by the matching engine. Each match captures
 * the venue, format, timing, team assignments, and player confirmations.
 *
 * Design decisions:
 * - confirmed_players is a denormalized counter for query efficiency.
 *   It must be maintained in sync with match_players.is_confirmed count.
 *   Module 2.7 (MatchConfirmationService) handles this via transactions.
 * - group_chat_id is populated by external chat service when match is confirmed.
 * - OneToMany relations use lazy loading to prevent accidental N+1 queries
 *   and circular serialization issues.
 */
@Entity('matches')
@Index(['status'])
@Index(['startTime'])
@Index(['venueId', 'startTime'])
@Index(['regionCode'])
export class Match {
  @PrimaryGeneratedColumn('increment', { type: 'bigint' })
  id!: number;

  @Column({
    name: 'venue_id',
    type: 'bigint',
    nullable: false,
  })
  venueId!: number;

  @ManyToOne(() => Venue, { onDelete: 'NO ACTION' })
  @JoinColumn({ name: 'venue_id' })
  venue!: Venue;

  @Column({
    name: 'format_id',
    type: 'bigint',
    nullable: false,
  })
  formatId!: number;

  @ManyToOne(() => Format, { onDelete: 'NO ACTION' })
  @JoinColumn({ name: 'format_id' })
  format!: Format;

  @Column({
    name: 'start_time',
    type: 'timestamptz',
    nullable: false,
  })
  startTime!: Date;

  @Column({
    name: 'end_time',
    type: 'timestamptz',
    nullable: false,
  })
  endTime!: Date;

  @Column({
    type: 'enum',
    enum: MATCH_STATUSES,
    nullable: false,
    default: 'pending_confirmation',
  })
  status!: MatchStatus;

  @Column({
    name: 'team_count',
    type: 'int',
    nullable: false,
  })
  teamCount!: number;

  @Column({
    name: 'players_per_team',
    type: 'int',
    nullable: false,
  })
  playersPerTeam!: number;

  @Column({
    name: 'total_players',
    type: 'int',
    nullable: false,
  })
  totalPlayers!: number;

  /**
   * Denormalized counter: number of players with is_confirmed = true.
   * Must be kept in sync with match_players table via transactions.
   * Do not modify directly; use MatchConfirmationService methods.
   */
  @Column({
    name: 'confirmed_players',
    type: 'int',
    nullable: false,
    default: 0,
  })
  confirmedPlayers!: number;

  @Column({
    name: 'deposit_amount',
    type: 'decimal',
    precision: 10,
    scale: 2,
    nullable: false,
  })
  depositAmount!: number;

  /**
   * Group chat room ID, generated by external chat service when match is confirmed.
   * Populated by MatchConfirmationService; not user-settable.
   */
  @Column({
    name: 'group_chat_id',
    type: 'varchar',
    length: 100,
    nullable: true,
  })
  groupChatId!: string | null;

  @Column({
    name: 'region_code',
    type: 'varchar',
    length: 20,
    nullable: true,
  })
  regionCode!: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;

  @OneToMany(() => MatchPlayer, (mp) => mp.match, {
    cascade: true,
    lazy: true,
  })
  matchPlayers!: Promise<MatchPlayer[]>;

  @OneToMany(() => MatchTeam, (mt) => mt.match, {
    cascade: true,
    lazy: true,
  })
  matchTeams!: Promise<MatchTeam[]>;

  @OneToMany(() => MatchMessage, (msg) => msg.match, {
    cascade: true,
    lazy: true,
  })
  messages!: Promise<MatchMessage[]>;
}
