import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  VersionColumn,
  ManyToOne,
  JoinColumn,
  OneToMany,
  Index,
} from 'typeorm';
import { Venue } from '@modules/venues/entities/venue.entity';
import { Format } from '@modules/formats/entities/format.entity';
import { MatchPlayer } from './match-player.entity';
import { MatchTeam } from './match-team.entity';
import { MatchMessage } from '@modules/messages/entities/match-message.entity';
import { MatchStatus, MATCH_STATUSES } from '@shared/match';

/**
 * Match entity representing a basketball match.
 *
 * v2.0 重构：
 * - status 改为 7 状态（pending_players/pending_venue/confirmed/in_progress/completed/cancelled/expired）
 * - 新增 requiredPlayers（= teamCount * playersPerTeam）
 * - 新增 confirmDeadline（球员确认截止时间 = startTime - 1小时）
 * - 新增 venueConfirmDeadline（场地方确认截止时间 = 满员时刻 + 30分钟）
 * - 删除 totalPlayers（改用 requiredPlayers）
 * - 新增复合索引 (status, confirmDeadline)
 *
 * Design decisions:
 * - confirmed_players is a denormalized counter for query efficiency.
 * - group_chat_id is populated when match is confirmed.
 * - OneToMany relations use lazy loading to prevent N+1 queries.
 */
@Entity('matches')
@Index(['status'])
@Index(['startTime'])
@Index(['venueId', 'startTime'])
@Index(['regionCode'])
@Index(['status', 'confirmDeadline'])  // v2.0: 超时调度器复合索引
export class Match {
  @PrimaryGeneratedColumn('increment', { type: 'bigint' })
  id!: number;

  @Column({
    name: 'venue_id',
    type: 'bigint',
    nullable: false,
  })
  venueId!: number;

  @ManyToOne(() => Venue, { onDelete: 'NO ACTION' })
  @JoinColumn({ name: 'venue_id' })
  venue!: Venue;

  @Column({
    name: 'format_id',
    type: 'bigint',
    nullable: false,
  })
  formatId!: number;

  @ManyToOne(() => Format, { onDelete: 'NO ACTION' })
  @JoinColumn({ name: 'format_id' })
  format!: Format;

  @Column({
    name: 'start_time',
    type: 'timestamptz',
    nullable: false,
  })
  startTime!: Date;

  @Column({
    name: 'end_time',
    type: 'timestamptz',
    nullable: false,
  })
  endTime!: Date;

  @Column({
    type: 'enum',
    enum: MATCH_STATUSES,
    nullable: false,
    default: 'pending_players',  // v2.0: 候选比赛
  })
  status!: MatchStatus;

  @Column({
    name: 'team_count',
    type: 'int',
    nullable: false,
  })
  teamCount!: number;

  @Column({
    name: 'players_per_team',
    type: 'int',
    nullable: false,
  })
  playersPerTeam!: number;

  /**
   * v2.0: 所需球员总数 = teamCount * playersPerTeam。
   * 替代旧的 totalPlayers 字段。
   */
  @Column({
    name: 'required_players',
    type: 'int',
    nullable: false,
  })
  requiredPlayers!: number;

  /**
   * Denormalized counter: number of players with status = 'confirmed'.
   * Must be kept in sync with match_players table via transactions.
   * Do not modify directly; use MatchConfirmationService methods.
   *
   * Concurrency safety:
   * - Use SELECT ... FOR UPDATE (pessimistic lock) or version-based
   *   optimistic lock when updating this field.
   * - The `version` column below provides optimistic locking.
   * - Always update within a transaction.
   */
  @Column({
    name: 'confirmed_players',
    type: 'int',
    nullable: false,
    default: 0,
  })
  confirmedPlayers!: number;

  /**
   * Optimistic lock version for concurrent updates.
   * Incremented automatically on each update to prevent lost updates
   * when multiple players confirm simultaneously.
   */
  @VersionColumn({ name: 'version' })
  version!: number;

  /**
   * v2.0: 球员确认截止时间 = startTime - 1小时。
   * 由匹配引擎创建候选比赛时设置。
   */
  @Column({
    name: 'confirm_deadline',
    type: 'timestamptz',
    nullable: true,
  })
  confirmDeadline!: Date | null;

  /**
   * v2.0: 场地方确认截止时间 = 满员时刻 + 30分钟。
   * 由满员触发场地确认时设置。
   */
  @Column({
    name: 'venue_confirm_deadline',
    type: 'timestamptz',
    nullable: true,
  })
  venueConfirmDeadline!: Date | null;

  /**
   * Deposit amount per player. Stored as decimal in DB, exposed as string
   * in API to avoid floating-point precision issues.
   * Use transformer to convert between string (TS) and numeric (DB).
   */
  @Column({
    name: 'deposit_amount',
    type: 'decimal',
    precision: 10,
    scale: 2,
    nullable: false,
    transformer: {
      to: (value: string) => parseFloat(value),
      from: (value: number | string) =>
        typeof value === 'number' ? value.toFixed(2) : value,
    },
  })
  depositAmount!: string;

  /**
   * Group chat room ID, generated by external IM service when match is confirmed.
   * Populated by MatchConfirmationService when status transitions to 'confirmed'.
   * Not user-settable.
   *
   * 生成策略：比赛状态转为 'confirmed' 时，由 MatchService 调用外部 IM 服务
   * 创建群组后回填此字段。若 IM 服务调用失败，比赛确认事务应回滚。
   */
  @Column({
    name: 'group_chat_id',
    type: 'varchar',
    length: 100,
    nullable: true,
  })
  groupChatId!: string | null;

  @Column({
    name: 'region_code',
    type: 'varchar',
    length: 20,
    nullable: true,
  })
  regionCode!: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;

  @OneToMany(() => MatchPlayer, (mp) => mp.match, {
    cascade: true,
    lazy: true,
  })
  matchPlayers!: Promise<MatchPlayer[]>;

  @OneToMany(() => MatchTeam, (mt) => mt.match, {
    cascade: true,
    lazy: true,
  })
  matchTeams!: Promise<MatchTeam[]>;

  @OneToMany(() => MatchMessage, (msg) => msg.match, {
    cascade: true,
    lazy: true,
  })
  messages!: Promise<MatchMessage[]>;
}
